project:
  type: website
  output-dir: docs

website:
  title: "DSTBX2025"
  navbar:
    left: 
      - text: " "
        href: users.qmd
    right:
      - icon: github
        href: https://github.com/guebin/DSTBX2025
      - icon: youtube
        href: https://www.youtube.com/channel/UCQk9RyBNgXc7ORIsYlOfQrg/playlists?view=50&sort=dd&shelf_id=2        
format:
  html:
    theme: cosmo
    number-sections: true
    css: styles.css
    toc: true
    toc-location: right
    toc-depth: 2