cat ../day1hw/baek_gm.txt
cat ../day1hw/choyun.txt
cat ../day1hw/coco.txt
cat ../day1hw/daehyeon.txt
cat ../day1hw/guebin.txt
cat ../day1hw/handoehee.txt
cat ../day1hw/hyeonji.txt
cat ../day1hw/jeongmin.txt
cat ../day1hw/jinsil.txt
cat ../day1hw/junhan.txt
cat ../day1hw/leejjae.txt
cat ../day1hw/mingu.txt
cat ../day1hw/seongjoon.txt
cat ../day1hw/seunghoon.txt
cat ../day1hw/soonwon.txt
cat ../day1hw/suwhan.txt
